### ISSUE TITLE
[BUG][users] - Some usernames in all capital letters not being obfuscated

### ISSUE THREAD

**Issue by skhobbs18** [soscleaner/soscleaner#148]
This is related to https://github.com/soscleaner/soscleaner/issues/99

This still seems to be an issue.

I have found some places where it did remove them, and some where it did not.

Here is a line with both lowercase and uppercase:

~~~
2019-07-17T04:56:33.831174-04:00 localhost sshd[28322]: pam_vas: Authentication <succeeded passwordless> for <Active Directory> user: <user1> account: <CORP\USER1> service: <sshd> reason: <>
~~~

The same time stamp in the cleaned report has both cleaned.

~~~
2019-07-17T04:56:33.831174-04:00 obfuscatedhost1 obfuscateduser22[28322]: pam_vas: Authentication <succeeded passwordless> for <Active Directory> user: <obfuscateduser661> account: <CORP\obfuscateduser661> service: <obfuscateduser22> reason: <>
~~~

The log lines which only have a capital letter username seem to be ignored. 

~~~
2019-07-17T04:57:28.537708-04:00 localhost sshd[28514]: pam_vas: Authentication <succeeded passwordless> for <Active Directory> user: <USER1> account: <CORP\USER1> service: <sshd> reason: <>

2019-07-17T04:57:28.537708-04:00 obfuscatedhost1 obfuscateduser22[28514]: pam_vas: Authentication <succeeded passwordless> for <Active Directory> user: <USER1> account: <CORP\USER1> service: <obfuscateduser22> reason: <>
~~~

Howerver we still see the hostname and the sshd user being cleaned.

**Expected behavior**
Expect all user names to be removed regardless of case.

$ cat installed-rpms |grep sos
soscleaner-0.4.4-1.el7.noarch                               Wed Jul 17 04:58:39 2019
sos-3.6-17.el7_6.noarch                                     Fri May 10 16:05:00 2019

**Comment by slashdd** [comment]
Regex look good to me, the problem is before the regexp operate.

The problem is that UPPERCASE obfuscation will only happen if there was an lowercase occurrence in the same line before the UPPERCASE, do to the if statement above which check the user as added.

line 1 user1 USER1 - Will work
line 2 USER1 - Won't work
line 3 USER1 user1 USER1 - Will start working after user1 ONLY.
line 4 USER1 USER1 - Won't work

To confirmed my theory, I did the following as a debug exercise using the reproducer mentioned above
```
    def _sub_username(self, line):
        """Accepts a line from a file as input and replaces all occurrences of the users in the
        user_db with the obfuscated values.
        Returns the obfuscated line.
        """

        try:
            if self.user_count > 0:    # we have obfuscated keywords to work with
                for user, o_user in self.user_db.items():
-                    if user in line:
+                    if user.lower() or user.upper() in line:
                        line = re.sub(r'\b%s\b(?i)' % user, o_user, line)
                        self.logger.debug("Obfuscating User - %s > %s", user, o_user)

            return line
```
and it did the trick
`2019-07-17T04:57:28.537708-04:00 obfuscatedhost3 obfuscateduser27[28514]: pam_vas: Authentication <succeeded passwordless> for <Active Directory> user: <obfuscateduser29> account: <CORP\obfuscateduser29> service: <obfuscateduser27> reason: <>`

`2019-07-17T04:56:33.831174-04:00 obfuscatedhost3 obfuscateduser27[28322]: pam_vas: Authentication <succeeded passwordless> for <Active Directory> user: <obfuscateduser29> account: <CORP\obfuscateduser29> service: <obfuscateduser27> reason: <>`

So this confirm the bug and the reason why it happens.

Now I don't know if the if I made is the right way to fix it, this was only as a debugging exercise.
It only covers scenarios where user1 and USER1, but not User1 or uSer1, ....

I do more testing when time permit.

**Comment by slashdd** [comment]
I think the following should do the trick 

```
         try:
             if self.user_count > 0:    # we have obfuscated keywords to work with
                 for user, o_user in self.user_db.items():
-                    if user in line:
                         line = re.sub(r'\b%s\b(?i)' % user, o_user, line)
                         self.logger.debug("Obfuscating User - %s > %s", user, o_user)
```
I don't see why the if statement is necessary here.

**Comment by slashdd** [comment]
Testing the above code change 

## sosreport
```
var/log/syslog:user1 USER1
var/log/syslog:USER1 user1 USER1
var/log/syslog:USER1
var/log/syslog:user1
```
## soscleaner
```
var/log/syslog:obfuscateduser29 obfuscateduser29
var/log/syslog:obfuscateduser29 obfuscateduser29 obfuscateduser29
var/log/syslog:obfuscateduser29
var/log/syslog:obfuscateduser29
```

**Comment by slashdd** [comment]
Extra testing with mixed lower and upper case.

## sosreport
var/log/syslog:uSer1

## soscleaner
var/log/syslog:obfuscateduser29
