### ISSUE TITLE
[RFE] - Capture user data from local system

### ISSUE THREAD

**Issue by skhobbs18** [soscleaner/soscleaner#97]
**Is your feature request related to a problem? Please describe.**
When running soscleaner on a RHEL 6 system the usernames captured from lastlog are not in the sosreport itself.  Request the config file run last log each run to keep an updated list of usernames to obfuscate.

**Describe the solution you'd like**
for each run of the soscleaner utility a running file of usernames should be kept by running lastlog and directing output to a file.

lastlog |awk '{print $1}'

this command will output only usernames.

**Describe alternatives you've considered**
Having the config file run this each time, or running it live on the command line with the -U option
~~~
# lastlog |awk '{print $1}' >> /tmp/users.txt && soscleaner -U /tmp/users.txt /tmp/sosreport-test.01234-20190227085453.tar.xz
~~~
**Additional context**

**Comment by jduncan-rva** [comment]
We really don't have a mechanism for this, in particular, because we have no way to guarantee soscleaner is run on the host that the sosreport is for. 

The user file option: 

```
parser.add_option("-U", "--users-file", action="store", dest="users_file",
                            help="line-delimited list of users to obfuscate",
                            metavar="USERS_FILE")
```

is probably the best option in this case. The above command could easily generate a valid user file to be used for obfuscation. Going to close this for now. If that's insufficient, please reopen with add'l information.
